const sep_messages = ["Nice ass girl. Can't wait to fondle it when I get back", 
    'Sometimes I dont tell you how lucky I am to have you in my life. You very much complete me girlie. I miss you', 
    'GET OFF YOUR ASS BITCH. GIMME 30 SQUATS RN!',
    'Hmm the 4th. Not so lucky. Take care today girlie. ',
    'Did you have any chicken breast lately? Thats what I thought big back',
    'MUAH MUAH MUAH. Im probs dying of bad food in Birmingham. Pls eat well girlie',
    'Reminder to drink your water girlie :). Matcha is healthy too. ',
    'WOOOOOOOO TODAY WILL SURELY BE A BOUNTIFUL DAY. GO GET IT GIRL!',
    'You are one of a kind girl. Keep doing you',
    'Oh Goodiest Morning!! You better be reading this in the morning :)',
    '"I dropped my pen!" "can you help me get it" *bends over WOOOOOOOO',
    'This is random but dont you think I have the best tastebuds?',
    'Oof take care. Another potentially unlucky day. DEFY THE ODDS GIRL (cuz its the 13th)',
    'YOU GOT THIS I BELIEVE. IT DOESN"T MATTER WHAT HAPPENS',
    'Have you been eating well? Sleeping well? Playing well? Missing me well?',
    'NICE FACE WOMAN. SLURRPPPPPPPP',
    'I hope your day has the stability of a century old oak tree',
    'I think eating gyg would really slap today. Sus it out',
    'Anotherrr WATER REMINDER! 2L WOMAN. CAN YOU DO IT? YES YOU CAN',
    'GOOOD MORNINGGGG. So what fruit have you eaten today?',
    'So wanna watch some harry potter to become less of an uncultured swine?',
    'My girl is the best girl :)',
    'SUG IT SUG IT WOOOOOOOOOOOOOOOOOOOO SUG IT HARD',
    'goOODOoOODOD MORNING!! Whatever youre doing today Im sure youre gonna do well :)',
    'GoOOOoooOOOOD MONRING WOMAN. RISE AND SHINE. TIME TO GET SOME DUBS!!! WOOOO',
    'If today is going to be a hard day, just remember, my cock is also hard. Have a good day my girl :)',
    'So uhh English or Spanish AHAHAHAH',
    'Good morning my gurl :). I hope your day smells like fresh bakeries',
    'Get some matcha coffee. You deserve it woman :)',
    'You got a snatched waist, perfect face shape, round eyes. I still dont have your wechat',
    'I am probs missing you hard girlie. Dont forget about me pls ;)',
    'I love you girlie and I cant wait till I get back']

const oct_messages = ["HAPPY UNOFFICIAL 2 YEARS!!!!", 
    'Brightest mornings, brightest skies, brightest sun. Yes. I believe it will be beautiful', 
    'It would be really cool if you made cooked something today and showed me :)',
    'I love you girl. Girlie. Emily Chang. #mygurl',
    'Your smile is one of your best feature. Smile lots today.',
    'Clouds = cotton candy = something sweet. Hope your day is as sweet as the clouds',
    'Girlie check your screen time. Is it good? Is it bad? Lmk ',
    'Another day of praying for your health and happiness my woman',
    'Should we compile of things to do once I get back? Will you even be there?',
    'I am in severe drought of lack of girlie. Please provide relief.',
    'Were almost at the end of the year. Scary stuff woman. Hit today hard',
    '*slap *SLURP *MAUH heeheheheheheheh',
    'You better still be reading all these messages Im writing for you',
    'Girlie are you having fun? Is each day filled with yummy emotions?',
    'COME ON. LETS GO. YOU ARE EMILY CHANG. YOU GOT THIS. SAY IT WITH ME',
    'Aite I deem today a big back day. Go crazy girlie',
    'The fruit of today is a banana. You must consume a banana.',
    'I diagnose you with 3 hours of study today. Good luck woman',
    'To hit everyday with the conviction of someone sacrificing their life',
    'I love you girlie. Muah Muah. You are beautiful but realistic. Have fun but appreciate good things.',
    'Girlie you guide me a lot. Nothing has ever gone wrong when I do what you say',
    'SMASH TODAY. YOU GOT IT. YOU GONNA BEAT TODAY DOWN EASY PEASY',
    'Reminder to try something new every once in a while :)',
    'I wanna hold your hands. I wanna kiss your forehead. I wanna come home to gurl.',
    'Whatever youre doing today girl. I hope it goes well :)',
    'GAWRRRRR. You should send me a vid of you dancing',
    'WOOOOOOOOOOOOO HOOOOOOOOOOOOOO. Happy days?',
    'Hey baby. You da sexy. Whatchu doing later?',
    'Lets go to the beach and eat some fish n chips in sunset when im back',
    'HAVENT FORGOTTEN ABOUT ME RITE RITE',
    'I hope you have a good hair, skin and LIFE day my woman',
    'Can I get some fiery pictures please? The ones you cant show in public']

const nov_messages = ["I wanna kiss my gurl", 
    'You are a gift and blessing. A treasure and jewel in my life', 
    'Go eat some fruit. Treat yourself well.',
    'Have you drunk your water? Have you had something healthy? ',
    'Girlie if you are struggling with anything. Try to embrace the struggle :)',
    'What is the most recent show you watched?',
    'Matcha strawberry is healthy. You should make it at home ',
    'WE ARE CLOSE. WE ARE NOT LONG FROM RETURNING',
    'I hope you have a peaceful day :)',
    'May the clouds rain liquid gold in terms of personal growth',
    'LEMME SQUISH YOUR ARMS GAWRTRWRRWR',
    'Whats your fit for today?',
    'Girlie I really like your smile',
    'The leprechauns are dancing. The dragons are wriggling. The day is here. Go get it.',
    'Go give gumshara another go :)',
    'Is it good weather for watermelon yet?',
    'Can I get a pic of your bodacious booty',
    'Soooo have you pooped today? If so how was it?',
    'SUMMER SOON? WATERMELON AND MANGOES? HAPPY DAYS?',
    'That to do list you made for today? You gonna crush it woman',
    'I bet your makeup today is fr fr bussing. SLUURRPPP',
    'Eat a cucumber today?',
    '"Hi. I think you really cute. I was hoping to get your number" W RIZZ?',
    'The girl has a very bright, round smile. Its very nice',
    'Girl. Whatever you do. I support you. Even if ur hating on my chicken breast',
    'Girlie. You got this today. Whatever you doing. You CAN FUGGING DO IT',
    'Make sure to get some proper fresh air. Not just city air.',
    'You have not queefed since that time in the star hotel. Crazy.',
    'Gimme a photo pls. I wanna see you',
    'I got one of these for every month but DIDNT FORGET ME RITE',
    'Girlie you are smarter and more amazing than you realise',
    'You are a good person girlie. Truly. ']

const dec_messages = ["HAPPY 2 YEAR ANNIVERSARY MY GURL WOOOO. FUGGING DID IT! ", 
    "Nice ass girl. Can't wait to fondle it when I get back", 
    'Sometimes I dont tell you how lucky I am to have you in my life. You very much complete me girlie. I miss you',
    '"Shower WITHOUT ME???" "WHERE MY HUG AT"',
    'You girlie you know you pretty and sexy and smile like no other?',
    'MUAH MUAH MUAH mY GURL. Cant wait to see you SOOONONONONONONONONON!!! ',
    'Almost at the end of my classes. How are holidays treating you?',
    'If you are reading this. You finished third year. WE ARE OLD!',
    'Glizzy gobbler. Banana barbarian. Popsicle pervert.',
    'Cant wait to back and tame my bratty girlfriend',
    '*ass slap *brown hole insert *vigorous penetration',
    'Grrrr I wanna make food with the girl and watch Totoro. MMMMM.',
    'My girl is very beautiful. I lucky boi.',
    'You may be going to work today. BUT UR GOING TO GET THRU IT!',
    'I am proud to have you as my girlie woman',
    'Can I has the cherry and peach pic please?',
    'You should totally watch some anime with me',
    'When I see pink I think of the gurl',
    'Lots of social situations = lots of thinking about gurl',
    'I reckon today would be good weather for matcha and chicken breast',
    'WOOOO CHRISTMAS SOON. ARE YOU EXCITED WOMAN???',
    'I reckon today would be a decent beach day!',
    'OMGGG HOPE YOU GOT YOUR GIFTS READYY GILRIE',
    'HEHEHE TONIGHT IS THE NIGHTT!!!!!!',
    'WOOOOOOO MERRY CHRISTMAS MY WOMAN. WOOHOOOO',
    'Sexy bitch. MUAH',
    'Kevin from 4 months ago is writing this. Hopefully Im reading this next to my woman',
    'You are my most reliable source of joy :)) HEHE',
    'Girl why you always just so damn SNATCHED',
    'You look really nice in green dresses :)',
    'omg omg. here we go. here we go. SO BEGINS OUR FINAL YEAR!!']

const month = new Date().getMonth()
const day = new Date().getDate()

messages = dec_messages

if (month == 8) {
    messages = sep_messages
} else if (month == 9) {
    messages = oct_messages
} else if (month == 10) {
    messages = nov_messages
}

document.getElementById("daily-message").textContent = messages[day - 1]
